---
title: Examination-RMSCS
author: Jochem Tolsma
date: '2020-11-18'
slug: RMSCS2020
categories: []
tags: []
subtitle: 'Examination Ceremony Research Master Social and Cultural Science 2020'
summary: 'Parents, friends and foes,...if you want to view the presentations of the RMSCS graduates please follow this link: [livestream](http://www.ru.nl/over-ons/diensten-faciliteiten/vm/academiegebouw-berchmanianum/livestream-berchmanianum/)!'
authors: []
lastmod: '2020-11-18T15:49:37+02:00'
featured: no
iimage:
  caption: ''
  focal_point: ""
  placement: 1
  preview_only: false
projects: []
---

---  

# **LIVESTREAM**

Parents, friends and foes,...  

if you want to view the presentations of the RMSCS graduates please follow this link: [livestream](http://www.ru.nl/over-ons/diensten-faciliteiten/vm/academiegebouw-berchmanianum/livestream-berchmanianum/){target="_blank"}!

---   

# **PRESENTATIONS**

The presentation of the Examination Ceremony Research Master Social and Cultural Science 2020 can be found here: [presentations](.pdf).

---  

# **PROGRAMME**  

15.30|**Welcome**| 
-----|-----|-----
15.35|**Pieter van Lamoen**|laudatio: dr. Niels Spierings
15.45|**Jorrit Luimers**|laudatio: dr. Mark Visser
15.55|**Gwendolyn Taartmans**|laudatio: prof. dr. Marieke van den Brink
16.05|**Sara Wiertsema**|laudatio: prof. dr. Gerbert Kraaykamp
16.15|**Hannah Worringer**|laudatio: prof. dr. Marieke van den Brink
16.25|**MOSAIC**| 
16.35|**Rob Franken**|laudatio: dr. Hidde Bekhuis
16.45|**Gita Huijgen**|laudatio: dr. Lieselotte Blommaert
16.55|**Lincy Scholten**|laudatio: dr. Maurice Gesthuizen
17.05|**Arinda Sutantapreeda**|laudatio: dr. Laura Dobusch
17.15|**Thesis Prize Nominations and Procedure**| 
**17.20**|**Virtual Drinks**| 

---  
