---
title: examplermarkdown2
author: JochemTolsma
date: '2020-08-19'
slug: examplermarkdown
categories:
  - R
  - Social Networks
tags: []
linktitle: Examplermarkdown2

summary: ~
lastmod: '2020-08-19T08:27:34+02:00'

type: book
weight: 5


output:
  blogdown::html_page:
    highlight: "haddock"
    number_sections: yes
    self_contained: yes
    toc: true
    fig_width: 6
    dev: "svg"

---


<!--set global settings--> 
```{r, globalsettings, echo=FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE, cache=TRUE)
options(width = 100)
```


test met tekst

# test met header

## nog een test


```{r testcode1, results = 'hold' }
2 + 2
3 + 3
```

```{r testcode, results = 'hold' , class.source="watch-out"}
2 + 2
3 + 3
```


```{r class.source="bg-danger", class.output="bg-warning"}
mtcars[1:5, "mpg"]
```

> en wat is dit dan


```{r}
if (TRUE) {
  x <- 1:10
  x + 1
}
```



Latest Version: `r format(Sys.Date(), "%d-%m-%Y")`

Please email any comments to: j.tolsma@ru.nl	
